### ISSUE TITLE
Warning: Unexpected input(s) 'test-command'

### ISSUE THREAD

**Issue by holomekc** [ioBroker/testing-action-check#6]
Hi it seems that the v1 tags are not attached properly:

Warning: Unexpected input(s) 'test-command', valid inputs are ['node-version', 'install-command', 'package-cache', 'type-checking', 'type-checking-command', 'lint', 'lint-command']

```yaml
    steps:
      - uses: ioBroker/testing-action-check@v1
        with:
          node-version: 22.x
          install-command: 'corepack enable && yarn install'
          lint-command: 'yarn run lint'
          test-command: 'yarn run test:package'
          type-checking: true
          lint: true
```

Main action.yaml looks fine: https://github.com/ioBroker/testing-action-check/blob/master/action.yml

But v1, v1.0 and v1.0.6 do not
https://github.com/ioBroker/testing-action-check/blob/v1/action.yml
https://github.com/ioBroker/testing-action-check/blob/v1.0/action.yml

Can you release a new version, which allows to set the test-command?
